### PR TITLE
Webroot

### PR DESCRIPTION
**Pull request by xataz**
Hi,

Sorry for my bad english.

I tried to use up1 behind a reverse proxy, without use a sub-domain.
I propose a feature that might add a webroot directly in server.conf. I'm not a developer, this feature is not perfect.

Thanks for read, and sorry for my english.

Regards,
Xataz,

### CODE REVIEW

**Comment by k3d3** [comment]
From a primary glance, looks good to me. I'll let the others look over it before merging, though.

**Comment by andre-d** [comment]
I have to take a look at just making everything relative and fix the root
root problem.

**Comment by ultramancool** [comment]
Wouldn't relative paths be a better solution here?

**Comment by k3d3** [comment]
Relative paths will work on the Javascript side, but on the server side it'll still need to know where the absolute paths are

**Comment by ultramancool** [comment]
We're assuming this is being used with a  reverse proxy, which should be
able to do that.

**Comment by k3d3** [comment]
@xataz the reverse proxy you're using, does it allow you to rewrite URL paths? Something like nginx's `rewrite` parameter, as demonstrated here http://serverfault.com/questions/379675/nginx-reverse-proxy-url-rewrite

If so, we might want to drop the server-side stuff but keep the relative paths on the web side.

**Comment by xataz** [comment]
Exemple work with this feature : http://box.xataz.ovh/truc
It's works with nginx reverse proxy : 
```php
location /truc {
proxy_pass http://127.0.0.1:8080;
}
```

The problem with rewrite, is that it is rewrite /static and /i path, a conflict with another location is possible.
But if you are a example for nginx configuration without my feature, I'm interested :smile:. 


Sorry for my english again, i'm french.

**Comment by k3d3** [comment]
Hey xataz,

We're actually going to close this pull request, as we've revamped the server and are about to revamp the client UI code (for cleaner extensibility). We will keep in mind what you've added though, and will make the browser code work with non-root path.

Thanks for your PR!

**Pull request closed without merging**
